import { PCarClass } from "./p-car-class";
import { PCarColor } from "./p-car-color";
import { PCarConfig } from "./p-car-config";
import { PCarGas } from "./p-car-gas";
import { PCarLine } from "./p-car-line";
import { PCarMark } from "./p-car-mark";
import { PCarType } from "./p-car-type";
import { PInsurance } from "./p-insurance";
import { PSatellite } from "./p-satellite";
import { PThirdState } from "./p-third-state";
import { Third } from "./third";
import { Trailer } from "./trailer";

export interface Car {
    id:                  number;
    placa:               string;
    carmodel:            number;
    carmodelrep:         number;
    motornumber:         string;
    chasis:              string;
    carimage:            string;
    forminspeccion:      string;
    soatnumber:          string;
    soatini:             Date;
    soatfin:             Date;
    soatimage:           string;
    tecnomnumber:        string;
    tecnomini:           Date;
    tecnomfin:           Date;
    tecnomimage:         string;
    pesomax:             number;
    pesovacio:           number;
    capacidadcarga:      number;
    observations:        string;
    last_coord_lng:      string;
    last_coord_lat:      string;
    last_login:          Date;
    status:              number;
    otro_satelital:      string;
    website_satelital:   string;
    username:            string;
    password:            string;
    property_card_front: string;
    property_card_back:  string;
    createdAt:           Date;
    updatedAt:           Date;
    owner_id:            number;
    ownerId:             Third;
    tenedor_id:          number;
    tenedorId:           Third;
    driver_id:           number;
    driverId:            Third;
    carmark_id:          number;
    carmarkId:           PCarMark
    carline_id:          number;
    carlineId:           PCarLine;
    carcolor_id:         number;
    carcolorId:          PCarColor;
    carclass_id:         number;
    carclassId:          PCarClass;
    cargas_id:           number;
    carGasId:            PCarGas;
    cartype_id:          number;
    cartypeId:           PCarType;
    carconfig_id:        number;
    carconfigId:         PCarConfig;
    insurance_id:        number;
    insuranceId:         PInsurance;
    status_id:           number;
    statusId:            PThirdState;
    trailer_id:          number;
    trailerId:           Trailer;
    satelital_id:        number;
    satelitalId:         PSatellite;

}
