import { General } from "./general";
import { Headquarter } from "./headquarter";
import { PCarClass } from "./p-car-class";
import { PCarType } from "./p-car-type";
import { PPacking } from "./p-packing";
import { PProductChatacter } from "./p-product-chatacter";
import { PProductClassification } from "./p-product-classification";
import { PProductCode } from "./p-product-code";
import { PRequestStatus } from "./p-request-status";
import { Third } from "./third";

export interface Request {
    id:                        number;
    freight:                   string;
    quantity:                  number;
    date:                      Date;
    charge_time:               Date;
    date_discharge:            Date;
    discharge_time:            Date;
    product_value:             number;
    charge:                    number;
    discharge:                 number;
    others:                    number;
    total_charge:              number;
    source_retencion:          number;
    ica:                       number;
    retainer:                  number;
    total:                     number;
    total_fee:                 number;
    observations:              string;
    customer_reference:        string;
    active:                    boolean;
    time_agreement:            number;
    time_agreement2:           number;
    status:                    string;
    distance:                  string;
    verification_code:         string;
    verify:                    string;
    container:                 string;
    createdAt:                 Date;
    updatedAt:                 Date;
    third_id:                  number;
    thirdId:                   Third;
    origin_id:                 number;
    originId:                  Headquarter;
    destination_id:            number;
    destinationId:             Headquarter;
    cartype_id:                number;
    cartypeId:                 PCarType;
    carclass_id:               number;
    carclassId:                PCarClass;
    packing_id:                number;
    packingId:                 PPacking;
    productCharacters_id:      number;
    productCharactersId:       PProductChatacter;
    productClassifications_id: number;
    productClassificationsId:  PProductClassification;
    productCodes_id:           number;
    p_ProductCode:             PProductCode;
    negotiated_id:             number;
    negotiatedId:              General;
    modality_id:               number;
    modalityId:                General;
    status_id:                 number;
    statusId:                  PRequestStatus;
}
