import { City } from "./city";
import { Companie } from "./companie";
import { Department } from "./department";
import { PDocumentType } from "./p-document-type";
import { General } from "./general";
import { PAccountType } from "./p-account-type";
import { PBank } from "./p-bank";
import { PDocDriver } from "./p-doc-driver";
import { PEconomicActivities } from "./p-economic-activities";
import { PFiscalRegimes } from "./p-fiscal-regimes";
import { PThirdState } from "./p-third-state";
import { Profile } from "./profile";

export interface Third {
    id?:                            number;
    email?:                         string;
    active?:                        boolean;
    tenedor?:                       boolean;
    firstname?:                     string;
    lastname?:                      string;
    lastname2?:                     string;
    business_name?:                 string;
    image?:                         string;
    docid?:                         string;
    dv?:                            number;
    celular?:                       string;
    phone?:                         string;
    celular2?:                      string;
    address?:                       string;
    address_complement?:            string;
    numberaccount?:                 string;
    observations?:                  string;
    imageRut?:                      string;
    imageCc?:                       string;
    imagePg?:                       string;
    imageBalance?:                  string;
    imageRenta?:                    string;
    imageOtro?:                     string;
    drivinglicense?:                string;
    validitylicenceStart?:          Date;
    validitylicenceEnd?:            Date;
    referenceFamily?:               string;
    relationshipFamiy?:             string;
    referencefamilyCelular?:        string;
    referencePersonal?:             string;
    relationshipPersonal?:          string;
    referencepersonaCelular?:       string;
    workcargo1?:                    string;
    workcontact1?:                  string;
    workcelular1?:                  string;
    workcargo2?:                    string;
    workcontact2?:                  string;
    workcelular2?:                  string;
    image_cc_reverso?:              string;
    image_front_license?:           string;
    image_back_license?:            string;
    credit_limit?:                  string;
    filing_invoice_address?:        string;
    workReference1?:                Companie;
    work_reference1?:               string;
    workReference2?:                Companie;
    work_reference2?:               string;
    commercial_reference?:          string;
    commercial_reference_image?:    string;
    commercial_reference2?:         string;
    commercial_reference2_contact?: string;
    commercial_reference2_celular?: string;
    commercial_reference2_image?:   string;
    commercial_reference3?:         string;
    commercial_reference3_contact?: string;
    commercial_reference3_celular?: string;
    commercial_reference3_image?:   string;
    bank_reference_image?:          string;
    bank_reference2_image?:         string;
    datospersonales?:               boolean;
    datosfinacieros?:               boolean;
    datosdocumentos?:               boolean;
    datoslicencia?:                 boolean;
    datosreferencias?:              boolean;
    createdAt?:                     Date;
    updatedAt?:                     Date;
    tenedorId?:                     Third;
    tenedor_id?:                    number;
    doctype_id?:                    number;
    doctypeId?:                     PDocumentType
    profileId?:                     Profile
    profile_id?:                    number;
    departmentId?:                  Department;
    department_id?:                 number;
    cityId?:                        City
    city_id?:                       number;
    economicactivitiesId?:          PEconomicActivities;
    economicactivities_id?:         number;
    fiscalregimesId?:               PFiscalRegimes;
    fiscalregimes_id?:              number;
    typeorganizations_id?:          number;
    bank_id?:                       number;
    bankReference?:                 PBank;
    bank_reference?:                number;
    bankReference2 ?:               PBank;
    bank_reference2?:               number;
    typeaccountId?:                 PAccountType
    typeaccount_id?:                number;
    categorylicenceId?:             PDocDriver
    categorylicence?:               number;
    issuedId?:                      City; // Lugar de emision licencia
    issued?:                        number;
    paymentDeadline?:               General;
    payment_deadline?:              number;
    negociatedMargin?:              General;
    negociated_margin?:             number;
    p_ThirdStatesId?:               PThirdState;
    p_ThirdStates_id?:              number;
    filingCity?:                    City;
    filing_city?:                   number;
}
